asset:
  kinds:
    - Book
    - Periodical
    - Magazine
    - Newspaper
    - Compact Disc
    - DVD
  formats:
    - Paperback
    - Hardbound
    - Cased
  languages:
    - Malayalam
    - English
    - Hindi
    - Tamil
    - Kannada
    - Arabic
    - Other
  ratings:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10

format:
  date: 'yyyy-mm-dd'